<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BanksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('banks')->delete();

        DB::table('banks')->insert(array (
            0 =>
            array (
                'id' => 1,
                'country_id' => 80,
                'name' => 'Agricultural Development Bank',
                'short_code' => 'ADB',
                'swift_code' => 'ADNTGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            1 =>
            array (
                'id' => 2,
                'country_id' => 80,
                'name' => 'Access Bank Ghana Limited',
                'short_code' => 'ABN',
                'swift_code' => 'ABNGGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            2 =>
            array (
                'id' => 3,
                'country_id' => 80,
                'name' => 'ARB Apex Bank Limited',
                'short_code' => 'ARB',
                'swift_code' => 'AREXGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            3 =>
            array (
                'id' => 4,
                'country_id' => 80,
                'name' => 'Bank Of Africa',
                'short_code' => 'BOA',
                'swift_code' => 'AMMAGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            4 =>
            array (
                'id' => 5,
                'country_id' => 80,
                'name' => 'Bank Of Baroda Ghana Limited',
                'short_code' => 'BOB',
                'swift_code' => 'BARBGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            5 =>
            array (
                'id' => 6,
                'country_id' => 80,
                'name' => 'Bank Of Ghana',
                'short_code' => 'BOG',
                'swift_code' => 'BAGHGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            6 =>
            array (
                'id' => 7,
                'country_id' => 80,
                'name' => 'Barclay Bank Of Ghana Ltd.',
                'short_code' => 'BAR',
                'swift_code' => 'BARCGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            7 =>
            array (
                'id' => 8,
                'country_id' => 80,
                'name' => 'BSIC Ghana Ltd.',
                'short_code' => 'BSIC',
                'swift_code' => 'BSAHGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            8 =>
            array (
                'id' => 9,
                'country_id' => 80,
                'name' => 'CAL Bank Limited',
                'short_code' => 'CAL',
                'swift_code' => 'ACCCGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            9 =>
            array (
                'id' => 10,
                'country_id' => 80,
                'name' => 'Ecobank Ghana',
                'short_code' => 'ECO',
                'swift_code' => 'ECOCGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            10 =>
            array (
                'id' => 11,
                'country_id' => 80,
                'name' => 'Enerygy Bank Ghana Limited',
                'short_code' => 'ENRB',
                'swift_code' => 'ENRBGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            11 =>
            array (
                'id' => 12,
                'country_id' => 80,
                'name' => 'Fidelity Bank Limited',
                'short_code' => 'FBL',
                'swift_code' => 'FBLIGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            12 =>
            array (
                'id' => 13,
                'country_id' => 80,
                'name' => 'First Atlantic Bank Limited',
                'short_code' => 'FAB',
                'swift_code' => 'FAMCGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            13 =>
            array (
                'id' => 14,
                'country_id' => 80,
                'name' => 'First Capital Plus Bank Limited',
                'short_code' => 'FCPB',
                'swift_code' => 'FCPBGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            14 =>
            array (
                'id' => 15,
                'country_id' => 80,
                'name' => 'Ghana Commerical Bank Limited',
                'short_code' => 'GCB',
                'swift_code' => 'GHCBGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            15 =>
            array (
                'id' => 16,
                'country_id' => 80,
                'name' => 'Guarantee Trust Bank Ghana Ltd.',
                'short_code' => 'GTB',
                'swift_code' => 'GTBIGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            16 =>
            array (
                'id' => 17,
                'country_id' => 80,
                'name' => 'HFC Bank Ghana Ltd.',
                'short_code' => 'HFC',
                'swift_code' => 'HFCAGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            17 =>
            array (
                'id' => 18,
                'country_id' => 80,
                'name' => 'International Commercial Bank',
                'short_code' => 'ICB',
                'swift_code' => 'INCEGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            18 =>
            array (
                'id' => 19,
                'country_id' => 80,
                'name' => 'National Investment Bank',
                'short_code' => 'NIB',
                'swift_code' => 'NIBGGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            19 =>
            array (
                'id' => 20,
                'country_id' => 80,
                'name' => 'Prudential Bank Limited',
                'short_code' => 'PBL',
                'swift_code' => 'PUBKGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            20 =>
            array (
                'id' => 21,
                'country_id' => 80,
                'name' => 'Societe Generale Ghana Limited',
                'short_code' => 'SG',
                'swift_code' => 'SSEBGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            21 =>
            array (
                'id' => 22,
                'country_id' => 80,
                'name' => 'Stanbic Bank Ghana Limited',
                'short_code' => 'SB',
                'swift_code' => 'SBICGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            22 =>
            array (
                'id' => 23,
                'country_id' => 80,
                'name' => 'Standard Chartered Bank Ghana',
                'short_code' => 'SCB',
                'swift_code' => 'SCBLGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            23 =>
            array (
                'id' => 24,
                'country_id' => 80,
                'name' => 'The Royal Bank',
                'short_code' => 'TRB',
                'swift_code' => 'TRBGGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            24 =>
            array (
                'id' => 25,
                'country_id' => 80,
                'name' => 'The Trust Bank Ltd.',
                'short_code' => 'TB',
                'swift_code' => 'TRBLGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            25 =>
            array (
                'id' => 26,
                'country_id' => 80,
                'name' => 'Unibank Ghana Ltd.',
                'short_code' => 'UNI',
                'swift_code' => 'UBGHGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            26 =>
            array (
                'id' => 27,
                'country_id' => 80,
                'name' => 'United Bank for Africa Ghana Ltd.',
                'short_code' => 'UBA',
                'swift_code' => 'STBGGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            27 =>
            array (
                'id' => 28,
                'country_id' => 80,
                'name' => 'Universal Merchant Bank Limited',
                'short_code' => 'UMB',
                'swift_code' => 'MBGHGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            28 =>
            array (
                'id' => 29,
                'country_id' => 80,
                'name' => 'UT Bank Ltd.',
                'short_code' => 'UT',
                'swift_code' => 'UTBKGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            29 =>
            array (
                'id' => 30,
                'country_id' => 80,
                'name' => 'Zenith Bank Ghana Limited',
                'short_code' => 'ZB',
                'swift_code' => 'ZEBLGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
            30 =>
            array (
                'id' => 31,
                'country_id' => 80,
                'name' => 'GN Bank Ghana Limited',
                'short_code' => 'GNB',
                'swift_code' => 'GNBGGHAC',
                'address' => NULL,
                'phone_numbers' => NULL,
                'email' => NULL,
                'created' => NULL,
                'modifid' => NULL,
                'deleted' => 0,
            ),
        ));


    }
}
